name: System Tests

on:
  push:
    branches:
      - e2e-test

jobs:
  system_tests:
    name: Run System Tests
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install npm packages
        run: npm install
        working-directory: ./

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Precompile assets
        run: bin/vite build

      - name: Run System Specs
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: bundle exec parallel_rspec --pattern "spec/system/.*_spec\.rb"
